name: Test Save and Store Environment Variables

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            token: ${{ secrets.GITHUB_TOKEN }}   

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Retrieve and print latest tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "Latest tag: $latest_tag"

      - name: Run Save and Store Environment Variables Action
        uses: ./  # This assumes the action is defined in the root of the repository
        with:
          image_base: 'nodejs-base'
          image_version: 'v1-base'
          job_type: 'build'
          prefix: 'custom-prefix'

      - name: Print Environment Variables
        run: |
          echo "APP_NAME=${{ env.APP_NAME }}"
          echo "SAFE_BASENAME=${{ env.SAFE_BASENAME }}"
          echo "BUILDER_IMAGE_VERSION=${{ env.BUILDER_IMAGE_VERSION }}"
          echo "BUILD_ID=${{ env.BUILD_ID }}"
          echo "BUILDER_ID=${{ env.BUILDER_ID }}"
          echo "ARTIFACT_DIR=${{ env.ARTIFACT_DIR }}"
          echo "NEXT_VERSION=${{ env.NEXT_VERSION }}"
